name: payjp_flutter
version: 0.7.1
description: A Flutter plugin for PAY.JP Mobile SDK.
homepage: https://github.com/payjp/payjp-flutter-plugin
repository: https://github.com/payjp/payjp-flutter-plugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.1.1
  built_collection: ^5.1.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.pay.flutter
        pluginClass: PayjpFlutterPlugin
      ios:
        pluginClass: PayjpFlutterPlugin
